### PR TITLE
fix(lib/index.ts): replace fs-extra with fs

### LINKED ISSUE #1: Error: Cannot find module `fs-extra`
- **I'm submitting a ...**
  - [x] bug report

- **Summary**
Running `npx prisma-schema-sorter sort --schema="./prisma/schema.prisma"` returns the following error:
```
Cannot find module 'fs-extra'
Require stack:
- /Users/USER/.npm/_npx/5789/lib/node_modules/prisma-schema-sorter/build/main/lib/index.js
- /Users/USER/.npm/_npx/5789/lib/node_modules/prisma-schema-sorter/build/main/bin/cli.js
```

I'm running on node v14.17.1 and npm v6.14.3 and MacOS v12

### PR DESCRIPTION
**Pull request by MohannadBahaa**
replace reading and writing files module from fs-extra to fs

fix #1

- **What kind of change does this PR introduce?
Bug fix

- **What is the current behaviour?**
#1 

- **What is the new behaviour (if this is a feature change)?**
replace fs-extra with fs

- **Other Information**:

### CODE REVIEW

**Comment by omar-dulaimi** [comment]
@MohannadBahaa Thank you!

Released in 1.3.4

File: src/lib/index.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import { readFile, writeFile } from 'fs-extra';
+import { promises as fs } from 'fs';
```
Comment (ruheni) [inline src/lib/index.ts:1]: Any reason you're importing `import { promises as fs} from 'fs';` here?

My suggestion would be to rename the import here `import * as fs from 'fs';` and use `fs.promises.writeFile(...)`.  

Alternatively, you could make the import alias to be something like `import { promises as fsPromises } from 'fs';` 🤔

Comment (MohannadBahaa) [reply src/lib/index.ts:1]: @ruheni Thank you for the feedback I would rather use
` import { promises as fsPromises } from 'fs';`  
instead of 
`  import * as fs from 'fs';
`  
BTW the event today was awesome 👍🏻
